//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandav.NAP.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public Nullable<int> CustomerId { get; set; }
        public int JobDetailId { get; set; }
        public string Particular { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Size { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual inDesign inDesign { get; set; }
        public virtual inDispatch inDispatch { get; set; }
        public virtual inPackaging inPackaging { get; set; }
        public virtual inPayment inPayment { get; set; }
        public virtual inPrinting inPrinting { get; set; }
        public virtual JobDetailInfo JobDetailInfo { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual User User { get; set; }
    }
}
