//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mandav.NAP.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetailInfo
    {
        public int JobDetailInfoId { get; set; }
        public string DetailType { get; set; }
        public Nullable<int> JobDetailId { get; set; }
        public string Detail { get; set; }
    
        public virtual JobDetail JobDetail { get; set; }
    }
}
